name: fatevae
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.13
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - h5py
  - anndata
  - scanpy>=1.11
  - pytorch>=2.5
